//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSpeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agents()
        {
            this.Sale = new HashSet<Sale>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string LogoPath { get; set; }
        public string UrAddress { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Director { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public Nullable<int> TypeAgentID { get; set; }
        public int ValueSale { get; set; }
        public float Discount { get; set; }

        public string AllLogoPath { get; set; }


        public virtual TypeAgent TypeAgent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sale { get; set; }
    }
}
