//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSpeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> AgentsID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> ValueProduct { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual Product Product { get; set; }
    }
}
